In [60]:
import pandas as pd

In [75]:
data = pd.read_csv('../data/raw/Dataset1.csv')
data.head()

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

In [62]:
data.columns

Index(['SN', 'Train_No', 'Station_Code', '1A', '2A', '3A', 'SL',
       'Station_Name', 'Route_Number', 'Arrival_time', 'Departure_Time',
       'Distance'],
      dtype='object')

In [63]:
data.shape

(186074, 12)

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186074 entries, 0 to 186073
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   SN              186074 non-null  int64
 1   Train_No        186074 non-null  int64
 2   Station_Code    186074 non-null  object
 3   1A              186074 non-null  int64
 4   2A              186074 non-null  int64
 5   3A              186074 non-null  int64
 6   SL              186074 non-null  int64
 7   Station_Name    186074 non-null  object
 8   Route_Number    186074 non-null  int64
 9   Arrival_time    186074 non-null  object
 10  Departure_Time  186074 non-null  object
 11  Distance        186074 non-null  int64
dtypes: int64(8), object(4)
memory usage: 17.0+ MB

In [65]:
data.describe()

,SN,Train_No,1A,2A,3A,SL,Route_Number,Distance
count,186074.000000,186074.000000,186074.000000,186074.000000,186074.000000,186074.000000,186074.0,186074.000000
mean,13.914695,42157.747455,1506.769189,1225.415351,944.061513,662.735777,1.0,281.353838
std,12.779368,25090.080221,2418.719821,1934.975856,1451.231892,967.524012,0.0,483.743964
min,1.000000,107.000000,100.000000,100.000000,100.000000,100.000000,1.0,0.000000
25%,5.000000,17225.000000,215.000000,192.000000,169.000000,146.000000,1.0,23.000000
50%,11.000000,40050.000000,465.000000,392.000000,319.000000,246.000000,1.0,73.000000
75%,18.000000,57550.000000,1555.000000,1264.000000,973.000000,682.000000,1.0,291.000000
max,118.000000,99908.000000,21400.000000,17140.000000,12880.000000,8620.000000,1.0,4260.000000

In [66]:
data.isnull().sum()

SN                0
Train_No          0
Station_Code      0
1A                0
2A                0
3A                0
SL                0
Station_Name      0
Route_Number      0
Arrival_time      0
Departure_Time    0
Distance          0
dtype: int64

In [67]:
data.duplicated().sum()

np.int64(0)

In [68]:
data.head(4)

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78

In [69]:
data.dtypes

SN                 int64
Train_No           int64
Station_Code      object
1A                 int64
2A                 int64
3A                 int64
SL                 int64
Station_Name      object
Route_Number       int64
Arrival_time      object
Departure_Time    object
Distance           int64
dtype: object

In [70]:
data['Station_Name'] = data['Station_Name'].str.strip().str.title()

data.drop('Station_Code', axis = 1, inplace = True)

In [71]:
data.dtypes

SN                 int64
Train_No           int64
1A                 int64
2A                 int64
3A                 int64
SL                 int64
Station_Name      object
Route_Number       int64
Arrival_time      object
Departure_Time    object
Distance           int64
dtype: object

In [72]:
data.head(5)

,SN,Train_No,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,100,100,100,100,Sawantwadi R,1,00:00:00,10:25:00,0
1,2,107,260,228,196,164,Thivim,1,11:06:00,11:08:00,32
2,3,107,345,296,247,198,Karmali,1,11:28:00,11:30:00,49
3,4,107,490,412,334,256,Madgoan Jn.,1,12:10:00,00:00:00,78
4,1,108,100,100,100,100,Madgoan Jn.,1,00:00:00,20:30:00,0

In [73]:
data.to_csv("../data/processed/cleaned_dataset.csv")

In [77]:
data.head()

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

In [82]:
train = data.groupby('Train_No')['Station_Name'].agg(['first','last'])
train

                 first          last
Train_No
107       SAWANTWADI R   MADGOAN JN.
108        MADGOAN JN.  SAWANTWADI R
128        MADGOAN JN.   CHHATRAPATI
290       DELHI-SAFDAR  DELHI-SAFDAR
401         AURANGABAD  VARANASI JN.
...                ...           ...
99904         PUNE JN.      TALEGAON
99905         TALEGAON  SHIVAJINAGAR
99906         PUNE JN.      TALEGAON
99907         TALEGAON      PUNE JN.
99908         PUNE JN.      TALEGAON

[11113 rows x 2 columns]

In [99]:
stop = data.groupby('Train_No').size().reset_index(name = 'No_of_Stops')
stop

       Train_No  No_of_Stops
0           107            4
1           108            4
2           128           22
3           290           14
4           401           12
...         ...          ...
11108     99904           12
11109     99905           11
11110     99906           12
11111     99907           12
11112     99908           12

[11113 rows x 2 columns]

In [91]:
stops = data.groupby('Train_No')['Distance'].agg(['max','min'])
stops

           max  min
Train_No
107         78    0
108         83    0
128        978    0
290       2694    0
401       1618    0
...        ...  ...
99904       34    0
99905       31    0
99906       34    0
99907       34    0
99908       34    0

[11113 rows x 2 columns]

In [104]:
max_stops = stop.loc[stop['No_of_Stops'].idxmax()]
min_stops = stop.loc[stop['No_of_Stops'].idxmax()]

print("Train with Maximum Stops:")
print(max_stops)

print("\nTrain with Minimum Stops:")
print(min_stops)

Train with Maximum Stops:
Train_No       53041
No_of_Stops      118
Name: 5977, dtype: int64

Train with Minimum Stops:
Train_No       53041
No_of_Stops      118
Name: 5977, dtype: int64